### PR TITLE
use non-integer number for cell vectors

### PR DESCRIPTION
**Pull request by ltalirz**

### CODE REVIEW

**Comment by asle85** [comment]
The test is actually failing, so your changes are detecting issue #19 .
Since we are changing the data, we have to run the tests first with the ``--force-regen`` flag which will automatically update the ``test_converters/test_send_valid_structure_xyz_ase_test_xyz_.csv`` file with the new non-integer data. The updated version of the csv file has to be committed as well in this branch.

**Comment by ltalirz** [comment]
Great!

If it's not too expensive, perhaps tests on github could always run with `--force-regen`?

**Comment by asle85** [comment]
I'm not sure. As far as I've understood, we should run the tests with the `--force-regen` flag only when there is a change in the data.
But I notice now that the changes in the test should go together with the update in the code (pull request #20 ). In this way, the tests run the updated code and generate the correct `test_send_valid_structure_xyz_ase_test_xyz_.csv` file (using the `--force-regen`) against which the data parsed in the tests is compared. Now the reference parsed data in the csv is incorrect because it was obtained with the bugged parser.
If instead we only modify the code for the parser, this shouldn't change the reference parsed data in the csv. In the unlucky case we introduce a bug we should avoid the regeneration of the reference csv files.

**Comment by giovannipizzi** [comment]
Superseded by 0d4e4c3e8bfae567f13f378bd4b774b5a88c5ed4 - as @asle85 mentioned, the fix of #19 wasn't yet done, so the new input was still validating returning "4.0", and validating correctly against the old reference data

**Comment by giovannipizzi** [comment]
(Thanks @ltalirz and @asle85 !)

**Pull request closed without merging**
